### ISSUE TITLE
[Error report] java.lang.NullPointerException: Parameter specified as non-null is null: method com.intellij.ide.plugins.PluginManagerCore.isPluginInstalled, parameter id

### ISSUE THREAD

**Issue by daniil4jk** [vaadin/intellij-plugin#216] opened 2024-12-12 11:47 UTC
Plugin version: **1.4.2**
IDE version: **IntelliJ IDEA 2024.3**
OS: **Windows 10**

Stacktrace:
```
java.lang.NullPointerException: Parameter specified as non-null is null: method com.intellij.ide.plugins.PluginManagerCore.isPluginInstalled, parameter id
	at com.intellij.ide.plugins.PluginManagerCore.isPluginInstalled(PluginManagerCore.kt)
	at com.intellij.ide.plugins.PluginManager.isPluginInstalled(PluginManager.java:56)
	at com.vaadin.plugin.utils.VaadinProjectUtilKt.hasEndpoints(VaadinProjectUtil.kt:86)
	at com.vaadin.plugin.ui.VaadinStatusBarWidget.getTooltipText(VaadinStatusBarWidget.kt:50)
	at com.intellij.openapi.wm.impl.status.IconPresentationComponent$1.invoke(IdeStatusBarImpl.kt:970)
	at com.intellij.openapi.wm.impl.status.IconPresentationComponent$1.invoke(IdeStatusBarImpl.kt:970)
	at com.intellij.openapi.wm.impl.status.TextPanel.getToolTipText(TextPanel.kt:56)
	at java.desktop/javax.swing.JComponent.getToolTipText(JComponent.java:3109)
	at com.intellij.ide.IdeTooltipManager.isTooltipDefined(IdeTooltipManager.kt:428)
	at com.intellij.ide.IdeTooltipManager.showForComponent(IdeTooltipManager.kt:389)
	at com.intellij.ide.IdeTooltipManager.maybeShowFor(IdeTooltipManager.kt:376)
	at com.intellij.ide.IdeTooltipManager.eventDispatched$intellij_platform_ide_impl(IdeTooltipManager.kt:336)
	at com.intellij.ide.SwingTooltipManagerCustomizer.execute$lambda$2(IdeTooltipManager.kt:68)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2198)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2046)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4938)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4590)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:621)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$21(IdeEventQueue.kt:564)
	at com.intellij.openapi.app
```

**Comment by MarcinVaadin** [comment] 2024-12-12 11:56
Duplicate of https://github.com/vaadin/intellij-plugin/issues/212

**Closed by MarcinVaadin** 2024-12-12 11:56 UTC
