### ISSUE TITLE
[Error report] java.lang.RuntimeException: Cannot invoke (class=CopilotVaadinProjectListener, method=vaadinProjectDetected, topic=Vaadin project detected)

### ISSUE THREAD

**Issue by nextRainbow** [vaadin/intellij-plugin#126] opened 2024-10-10 09:06 UTC
Plugin version: **1.3.4**
IDE version: **IntelliJ IDEA 2023.3.7**
OS: **Windows 10**

Stacktrace:
```
java.lang.RuntimeException: Cannot invoke (class=CopilotVaadinProjectListener, method=vaadinProjectDetected, topic=Vaadin project detected)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy16/jdk.proxy16.$Proxy331.vaadinProjectDetected(Unknown Source)
	at com.vaadin.plugin.VaadinProjectDetector.doNotifyAboutVaadinProject(VaadinProjectDetector.kt:31)
	at com.vaadin.plugin.VaadinProjectDetector.execute(VaadinProjectDetector.kt:24)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:482)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(run activity), run activity, StandaloneCoroutine{Cancelled}@13b6049a, Dispatchers.Default]
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Write access is allowed inside write-action only (see Application.runWriteAction())

**Comment by MarcinVaadin** [comment] 2024-10-28 12:11
Duplicate of #134

**Closed by MarcinVaadin** 2024-10-28 12:11 UTC
Labels: bug, needs investigation
