### ISSUE TITLE
[Error report] java.lang.AssertionError: Wrong line separators: '...Properties\r\n#Mon Mar...' at offset 46

### ISSUE THREAD

**Issue by jfarjona** [vaadin/intellij-plugin#24] opened 2024-03-26 01:03 UTC
Plugin version: **1.0.2**
IDE version: **IntelliJ IDEA 2023.3.6**

Stacktrace:
```
java.lang.AssertionError: Wrong line separators: '...Properties\r\n

**Comment by MarcinVaadin** [comment] 2024-03-26 08:27
Thank you for reporting issue! Already fixed, new version will be published today.

Duplicate of https://github.com/vaadin/intellij-plugin/issues/19

**Closed** 2024-03-26 08:28 UTC
