### ISSUE TITLE
[Error report] com.intellij.diagnostic.PluginException: Write access is allowed inside write-action only (see Application.runWriteAction())

### ISSUE THREAD

**Issue by gdesveaux** [vaadin/intellij-plugin#208] opened 2024-12-10 19:00 UTC
Plugin version: **1.4.1**
IDE version: **IntelliJ IDEA 2024.3.1**
OS: **Mac OS X**

Stacktrace:
```
com.intellij.diagnostic.PluginException: Write access is allowed inside write-action only (see Application.runWriteAction())

**Comment by MarcinVaadin** [comment] 2024-12-11 07:58
Closing as it might be duplicate of #205 , if reason is different, please create new issue with full stacktrace.

**Closed by MarcinVaadin** 2024-12-11 07:58 UTC
